disabled_rules:
  - trailing_whitespace
  - line_length
  - name_identifier
  - identifier_name
  - force_cast
  - type_name
opt_in_rules:
  - empty_count
  - explicit_init
included:
  - .
excluded:
  - Pods
